- basename_vm: dbnode-dc1-
  num_vm: 1
  hostgroup: vbox-rac-dc1
  domain: internal.lab
  box: oravirt/ol73
  vagrant_user: vagrant
  vagrant_pass: vagrant
  #vagrant_private_key: /vagrant/base-provision/insecure_private_key
  ram: 6196
  cpu: 1
  base_pub_ip: 192.168.9.10
  #base_pub_ip_vip: 192.168.9.110
  #scan_addresses: 192.168.9.210,192.168.9.211
  #base_priv_ip: 172.16.9.10
  synced_folders:
     - {src: swrepo, dest: /media/swrepo}
  create_local_disk: true
  local_disks:
     - {name: u01, size: 75, count: 1}
  create_shared_disk: false
  shared_disks:
     - {name: crs, size: 8, count: 1}
     - {name: data, size: 8, count: 1}
     - {name: fra, size: 8, count: 1}
  provisioning: 
  provisioning_env_override: false

# - basename_vm: dbnode-dc2-
#   num_vm: 2
#   hostgroup: vbox-rac-dc2
#   domain: internal.lab
#   box: oravirt/ol73
#   vagrant_user: vagrant
#   vagrant_pass: vagrant
#   vagrant_private_key:
#   ram: 1024
#   cpu: 1
#   base_pub_ip: 192.168.8.10
#   base_pub_ip_vip: 192.168.8.110
#   scan_addresses: 192.168.8.210,192.168.8.211
#   base_priv_ip: 172.16.8.10
#   synced_folders:
#      - {src: /Users/miksan/Downloads/oracle, dest: /media/swrepo}
#   create_local_disk: true
#   local_disks:
#     - {name: u01, size: 75, count: 1}
#   create_shared_disk: false
#   shared_disks:
#      - {name: crs, size: 1, count: 1}
#      - {name: data, size: 1, count: 1}
#      - {name: fra, size: 1, count: 1}
#   provisioning: ansible-oracle/vbox-rac-dc2.yml
